--
-- packages/beehive/sql/beehive-create.sql
--
-- @author turani
-- @creation-date 2000-10-22
-- @cvs-id $Id$

create table beehive_tasks (     name varchar(300), num  integer,     problem   varchar(600),     forces  varchar(900),     rpt  varchar(500),     solution varchar(900)    );

create table beehive_pattern (    num  serial,    techniqe   varchar(50),    name   varchar(200),    roles varchar(300),    mx  varchar(10),    mn  varchar(10),    df  varchar(10),    t2  varchar(10),  t3  varchar(10),  t4  varchar(10),    t5  varchar(10),    t6  varchar(10),    t7  varchar(10),    t8  varchar(10),    t9  varchar(10),    t10  varchar(10),    t11  varchar(10),    t12  varchar(10),    t13  varchar(10),    t14  varchar(10),    t15  varchar(10),    t17 varchar(10),    t18 varchar(10),    t19  varchar(10),    t20  varchar(10),    t22  varchar(10),    t23  varchar(10),    t24  varchar(10),    t26  varchar(10),    t27  varchar(10),    t28  varchar(10),    t29 varchar(10),    t30 varchar(10),    t31  varchar(10),    t32  varchar(10),    t33  varchar(10),    t34  varchar(10),    t35  varchar(10),    t36  varchar(10),    t37  varchar(10),    t38  varchar(10),    adda1  varchar(10),    addv1  varchar(10),    adda2  varchar(10),    addv2  varchar(10),    adda3  varchar(10),    addv3  varchar(10),    ctype1  varchar(10),    ctype2  varchar(10),    ctype3  varchar(10),    controlld1  varchar(10),    controlld2  varchar(10),    btype1  varchar(10),    btype2  varchar(10), dtype1  varchar(10),    anon1  varchar(10),    anon2  varchar(10),    anon3  varchar(10),    anon4  varchar(10),    problem   varchar(200),    example  varchar(200),    context  varchar(200),    gstructure varchar(200),    solution varchar(3000), uses  varchar(200),  criticalthinking  varchar(10),  creativethinking  varchar(10), analyticalskills  varchar(10), decisionmaking  varchar(10), leadership varchar(10), timemanagement   varchar(10), oralcommunication  varchar(10),  writtencommunicatoin  varchar(10), reflecting varchar(10), searchingskills varchar(10), knowledgesharing varchar(10));


create table beehive_ses (    number  varchar(30),    tutor    varchar(60),    classname varchar(60),    stype   varchar(30),    name   varchar(200),    roles varchar(300),    mx  varchar(10),    mn  varchar(10),    df  varchar(10), timew varchar(10), datew varchar(30),    titlew varchar(200),    t2  varchar(10), t3  varchar(10),   t4  varchar(10),    t5  varchar(10),    t6  varchar(10),    t7  varchar(10),    t8  varchar(10),    t9  varchar(10),    t10  varchar(10),    t11  varchar(10),    t12  varchar(10),    t13  varchar(10),    t14  varchar(10),    t15  varchar(10),    t17 varchar(10),    t18 varchar(10),    t19  varchar(10),    t20  varchar(10),    t22  varchar(10),    t23  varchar(10),    t24  varchar(10),    t26  varchar(10),    t27  varchar(10),    t28  varchar(10),    t29 varchar(10),    t30 varchar(10),    t31  varchar(10),    t32  varchar(10),    t33  varchar(10),    t34  varchar(10),    t35  varchar(10),    t36  varchar(10),    t37  varchar(10),    t38  varchar(10),    adda1  varchar(10),    addv1  varchar(10),    adda2  varchar(10),    addv2  varchar(10),    adda3  varchar(10),    addv3  varchar(10),    ctype1  varchar(10),    ctype2  varchar(10),    ctype3  varchar(10),    controlld1  varchar(10),    controlld2  varchar(10),    sessioninfo         varchar(10000),     roleinfo         varchar(5000),     ih          varchar(70), groupinfo   varchar(10000),  el  varchar(300), ideasnumber      varchar(10), ideastext    varchar(10000), largesharedtext         varchar(5000), smallsharedtext    varchar(5000), individualtext    varchar(5000),smallannotatedtext    varchar(5000),largeannotatedtext    varchar(5000),sln    varchar(10),fln    varchar(10), slnw    varchar(10),   btype1  varchar(10),    btype2  varchar(10),  dtype1  varchar(10),        anon1  varchar(10),    anon2  varchar(10), anon3  varchar(10),    anon4  varchar(10),   criticalthinking  varchar(10),  creativethinking  varchar(10), analyticalskills  varchar(10),decisionmaking  varchar(10), leadership varchar(10), timemanagement   varchar(10), oralcommunication  varchar(10),  writtencommunicatoin  varchar(10),reflecting varchar(10), searchingskills varchar(10), knowledgesharing varchar(10),solution varchar(3000)  );

create table beehive_patscript (      tname  varchar(100),    techniqe   varchar(50),    n1  integer,    ins1  varchar(500),    tr1  varchar(100),    tl1  varchar(20),    tool1  varchar(50),    n2  integer,    ins2  varchar(500),    tr2  varchar(100),    tl2  varchar(20),    tool2  varchar(50),    n3  integer,    ins3  varchar(500),    tr3  varchar(100),    tl3  varchar(20),    tool3  varchar(50),    n4  integer,    ins4  varchar(500),    tr4  varchar(100),    tl4  varchar(20),    tool4  varchar(50),    n5  integer,    ins5  varchar(500),    tr5  varchar(100),    tl5  varchar(20),    tool5  varchar(50),    n6  integer,    ins6  varchar(500),    tr6  varchar(100),    tl6  varchar(20),    tool6  varchar(50),    n7  integer,    ins7  varchar(500),    tr7  varchar(100),    tl7  varchar(20),    tool7  varchar(50),    n8  integer,    ins8  varchar(500),    tr8  varchar(100),    tl8  varchar(20),    tool8  varchar(50),    n9  integer,    ins9  varchar(500),    tr9  varchar(100),    tl9  varchar(20),    tool9  varchar(50),    n10  integer,    ins10  varchar(500),    tr10  varchar(100),    tl10  varchar(20),    tool10  varchar(50),     n11  integer,    ins11  varchar(500),    tr11  varchar(100),    tl11  varchar(20),    tool11  varchar(50),    n12  integer,    ins12  varchar(500),    tr12  varchar(100),    tl12  varchar(20),    tool12  varchar(50),    n13  integer,    ins13  varchar(500),    tr13  varchar(100),    tl13  varchar(20),    tool13  varchar(50),    n14  integer,    ins14  varchar(500),    tr14  varchar(100),    tl14  varchar(20),    tool14  varchar(50),    n15  integer,    ins15  varchar(500),    tr15  varchar(100),    tl15  varchar(20),    tool15  varchar(50),    n16  integer,    ins16  varchar(500),    tr16  varchar(100),    tl16  varchar(20),    tool16  varchar(50),    n17  integer,    ins17  varchar(500),    tr17  varchar(100),    tl17  varchar(100),    tool17  varchar(50),    n18  integer,    ins18  varchar(500),    tr18  varchar(100),    tl18  varchar(20),    tool18  varchar(50),    n19  integer,    ins19  varchar(500),    tr19  varchar(20),    tl19  varchar(20),    tool19  varchar(50),    n20  integer,    ins20  varchar(500),    tr20  varchar(100),    tl20  varchar(20),    tool20  varchar(50),     n21  integer,    ins21  varchar(500),    tr21  varchar(100),    tl21  varchar(20),    tool21  varchar(50),    n22  integer,    ins22  varchar(500),    tr22  varchar(100),    tl22  varchar(20),    tool22  varchar(50),    n23  integer,    ins23  varchar(500),    tr23  varchar(100),    tl23  varchar(20),    tool23  varchar(50),    n24  integer,    ins24  varchar(500),    tr24  varchar(100),    tl24  varchar(20),    tool24  varchar(50),    n25  integer,    ins25  varchar(500),    tr25  varchar(100),    tl25  varchar(20),    tool25  varchar(50));

create table beehive_emptypatscript (    tname  varchar(100),    techniqe   varchar(50),    n1  integer,    ins1  varchar(150),    tr1  varchar(20),    tl1  varchar(20),    tool1  varchar(50),    n2  integer,    ins2  varchar(150),    tr2  varchar(20),    tl2  varchar(20),    tool2  varchar(50),    n3  integer,    ins3  varchar(150),    tr3  varchar(20),    tl3  varchar(20),    tool3  varchar(50),    n4  integer,    ins4  varchar(150),    tr4  varchar(20),    tl4  varchar(20),    tool4  varchar(50),    n5  integer,    ins5  varchar(150),    tr5  varchar(20),    tl5  varchar(20),    tool5  varchar(50),    n6  integer,    ins6  varchar(150),    tr6  varchar(20),    tl6  varchar(20),    tool6  varchar(50),    n7  integer,    ins7  varchar(150),    tr7  varchar(20),    tl7  varchar(20),    tool7  varchar(50),    n8  integer,    ins8  varchar(150),    tr8  varchar(20),    tl8  varchar(20),    tool8  varchar(50),    n9  integer,    ins9  varchar(150),    tr9  varchar(20),    tl9  varchar(20),    tool9  varchar(50),    n10  integer,    ins10  varchar(150),    tr10  varchar(20),    tl10  varchar(20),    tool10  varchar(50),    n11  integer,    ins11  varchar(150),    tr11  varchar(20),    tl11  varchar(20),    tool11  varchar(50),    n12  integer,    ins12  varchar(150),    tr12  varchar(20),    tl12  varchar(20),    tool12  varchar(50),    n13  integer,    ins13  varchar(150),    tr13  varchar(20),    tl13  varchar(20),    tool13  varchar(50),    n14  integer,    ins14  varchar(150),    tr14  varchar(20),    tl14  varchar(20),    tool14  varchar(50),    n15  integer,    ins15  varchar(150),    tr15  varchar(20),    tl15  varchar(20),    tool15  varchar(50),    n16  integer,    ins16  varchar(150),    tr16  varchar(20),    tl16  varchar(20),    tool16  varchar(50),    n17  integer,    ins17  varchar(150),    tr17  varchar(20),    tl17  varchar(20),    tool17  varchar(50),    n18  integer,    ins18  varchar(150),    tr18  varchar(20),    tl18  varchar(20),    tool18  varchar(50),    n19  integer,    ins19  varchar(150),    tr19  varchar(20),    tl19  varchar(20),    tool19  varchar(50),    n20  integer,    ins20  varchar(150),    tr20  varchar(20),    tl20  varchar(20),    tool20  varchar(50),     n21  integer,    ins21  varchar(500),    tr21  varchar(100),    tl21  varchar(20),    tool21  varchar(50),    n22  integer,    ins22  varchar(500),    tr22  varchar(100),    tl22  varchar(20),    tool22  varchar(50),    n23  integer,    ins23  varchar(500),    tr23  varchar(100),    tl23  varchar(20),    tool23  varchar(50),    n24  integer,    ins24  varchar(500),    tr24  varchar(100),    tl24  varchar(20),    tool24  varchar(50),    n25  integer,    ins25  varchar(500),    tr25  varchar(100),    tl25  varchar(20),    tool25  varchar(50));

create table beehive_sesscript (    number   varchar(50),    n1  integer,    ins1  varchar(500),    tr1  varchar(100),    tl1  varchar(20),    tool1  varchar(50),    n2  integer,    ins2  varchar(500),    tr2  varchar(100),    tl2  varchar(20),    tool2  varchar(50),    n3  integer,    ins3  varchar(500),    tr3  varchar(100),    tl3  varchar(20),    tool3  varchar(50),    n4  integer,    ins4  varchar(500),    tr4  varchar(100),    tl4  varchar(20),    tool4  varchar(50),    n5  integer,    ins5  varchar(500),    tr5  varchar(100),    tl5  varchar(20),    tool5  varchar(50),    n6  integer,    ins6  varchar(500),    tr6  varchar(100),    tl6  varchar(20),    tool6  varchar(50),    n7  integer,    ins7  varchar(500),    tr7  varchar(100),    tl7  varchar(20),    tool7  varchar(50),    n8  integer,    ins8  varchar(500),    tr8  varchar(100),    tl8  varchar(20),    tool8  varchar(50),    n9  integer,    ins9  varchar(500),    tr9  varchar(100),    tl9  varchar(20),    tool9  varchar(50),    n10  integer,    ins10  varchar(500),    tr10  varchar(100),    tl10  varchar(20),    tool10  varchar(50),     n11  integer,    ins11  varchar(500),    tr11  varchar(100),    tl11  varchar(20),    tool11  varchar(50),    n12  integer,    ins12  varchar(500),    tr12  varchar(100),    tl12  varchar(20),    tool12  varchar(50),    n13  integer,    ins13  varchar(500),    tr13  varchar(100),    tl13  varchar(20),    tool13  varchar(50),    n14  integer,    ins14  varchar(500),    tr14  varchar(100),    tl14  varchar(20),    tool14  varchar(50),    n15  integer,    ins15  varchar(500),    tr15  varchar(100),    tl15  varchar(20),    tool15  varchar(50),    n16  integer,    ins16  varchar(500),    tr16  varchar(100),    tl16  varchar(20),    tool16  varchar(50),    n17  integer,    ins17  varchar(500),    tr17  varchar(100),    tl17  varchar(100),    tool17  varchar(50),    n18  integer,    ins18  varchar(500),    tr18  varchar(100),    tl18  varchar(20),    tool18  varchar(50),    n19  integer,    ins19  varchar(500),    tr19  varchar(20),    tl19  varchar(20),    tool19  varchar(50),    n20  integer,    ins20  varchar(500),    tr20  varchar(100),    tl20  varchar(20),    tool20  varchar(50),     n21  integer,    ins21  varchar(500),    tr21  varchar(100),    tl21  varchar(20),    tool21  varchar(50),    n22  integer,    ins22  varchar(500),    tr22  varchar(100),    tl22  varchar(20),    tool22  varchar(50),    n23  integer,    ins23  varchar(500),    tr23  varchar(100),    tl23  varchar(20),    tool23  varchar(50),    n24  integer,    ins24  varchar(500),    tr24  varchar(100),    tl24  varchar(20),    tool24  varchar(50),    n25  integer,    ins25  varchar(500),    tr25  varchar(100),    tl25  varchar(20),    tool25  varchar(50)    );

insert into beehive_emptypatscript (n1) values (1);


create table beehive_sessionIntraction (    sei      serial,    sname   varchar(100),    textdate   varchar(100),    type_Interaction varchar(100),    se     int,    student_response varchar(25000),   gr     int,      instruction_number  int  );





create table beehive_sesf ( snumber integer,     teacherid   integer);

create table beehive_sesstudents ( sesnumber integer,     stid   integer,  role  varchar(20), gr  integer,  sname  varchar(25) );

insert into beehive_pattern (num) values (0);

 
insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Ideas listing',26, 'How can learners posts their ideas on a posting chart?','Some pedagogical techniques require generating and posting ideas','To provide learners with a tool which holds the posted ideas from the group participants. Each idea is assigned with a sequential number for referencing. Ideas can be anonymous to ease the social pressure','Brainstorming Technique, Group nomination technique');

insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Controlling the timer',5, 'How can a facilitator time an activity? ','Most activity techniques require timing.  The timer is controlled  during the session by the facilitator in order for him to extend, or shorten the time of a certain step ',' To provide facilitators with a tool which that displays the duration on the top and show the time passed on the bottom. It should contain three buttons, start, pause ( to allow more time in that activity), and forward (to jump to the next activity) .','Optional in all pedagogical techniques');

insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Monitoring groups and providing guidance',9, 'How can a facilitator guide learners during the session?','Usually , learners need facilitators guidance to proceed smoothly in the session ',' facilitator can select the target that he would like to guide from a list box(group, role, or student). Then the facilitator will type the guiding text in a text box and sent it to the selected target. Also he can select which group to monitor form a list box which contain all active groups .','Optional in all pedagogical techniques');

insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Asking facilitator for help',8, 'How can learners ask for the facilitator help to clarify an issu, similar to face-to-face sessions?', 'Occasionally, learners would be able  to post their questions regarding  clarification of  unclear issues during the session',' Provide learners with a chat box where learners and facilitators can post their questions and answers during the session.  A buzz sound with every posting will help in  attracting the participants attention to that posting.','Optional in all pedagogical techniques');

insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Defining the objective of the session/Title',11, 'How can all session students view the main objective, title, or problem statement in clear way inside and outside session stage ?','facilitator needs to write down the objective, title, or problem statement in a very clear way so students can easily recognize and understand.',' Provide a separate text box with its own heading, so facilitator can type the title statement. Learners will engage in a session by clicking on the title. ','Mandatory  in all pedagogical techniques');


insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Providing the session Info',12, 'How can all session participants be provided with the same detailed information, explanation, and any supplementary information needed to conduct the desired collaborative activity ?','Usually when learners anticipates in a session, title or purpose might not be sufficient to understand the problem',' Provide a separate info text box to hold the information provided by facilitator in the design time. Students can view the information. ','Optional  in all pedagogical techniques');


insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Providing info/tasks to a Role',13, 'How can a specific role participants be provided with certain information needed to conduct their role?','In some techniques, certain information should be passed to certain roles  ' ,' Provide a separate info text box to hold the sub info provided by facilitator in the design time. The facilitator should also specify the target of each sub info. Students can only view the information that matches their roles. ','Usually in the Jigsaw, Role Playing techniques ');

insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Providing info/tasks to a group',4, 'How can a specific group participants be provided with certain information needed to conduct their tasks?','In some techniques, certain information should be passed to certain group  ' ,' Provide a separate info text box to hold the sub info provided by facilitator in the design time. The facilitator should also specify the target of each sub info. Students can only view the information that matches theirgroup number ','Usually in the buzz group  technique ');


insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Side note taking',31, 'How can learners to prepare and organize their thoughts during the session before presenting them to others?','Learner are required specially at the beginning of the session to think privately about a topic, problem, etc and to write down them down in a private box which will make it easier to copy to a chat box during the session  ' ,'Provide learners with a text box where they can write down their notes and ideas during the session. ','Optional in all pedagogical techniques');

insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Providing the session resource file',32, 'How can session participants be provided with more information from the facilitator ?','Occasionally, more information is  needed to conduct the desired session ' ,' Provide a separate info text box to hold the uploaded file provided by facilitator in the design time and to be shown to students at run  time at the session info page. ','Optional in all pedagogical techniques');

insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Providing a staged resource',33, 'How can media/animation/information be provided on a certain step during the session ?','Occasionally during the session, facilitator would like to show information after students had finished a certain step and might be followed by another activity step  ' ,' Provide a separate  text link to hold the links   which will be shown to students on the session stage at the specific step. ','Usually in the Video viewing, Case study techniques');

insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('White board drawing',20, 'How can a group of learners participate in a shared white board drawing ?','Some  activities imply that participants collaborate by using graphical communication with the ability to add a background image to annotate on  ' ,'Provide learners with a shared whitewboared  where  participants can draw lines or insert text during the session and an audio tool to communicate vocally while drawing. The whiteboard can be cleaned at any time by a clear button. ','Optional in all pedagogical techniques');


insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Providing the session description/rules/instructions',14, 'How can all session participants be provided with the same description/rules/instructions on how to conduct the desired collaboration activity?','Usually, pedagogical techniques need to be clearly explained  to learner  in order to perform the activity in a proper way  ' ,'Provide a separate info text box to hold the description/rules/instructions provided by facilitator. Student can view the information from the session info page ','Optional in all pedagogical techniques');



insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Giving a brief vocal overview',15, 'How can  facilitator provide an audio overview at the beginning of the collaboration activity?','For learners who are new in using and conducting online sessions, it will help if the facilitator provide a short vocal overview of what learners need to do on that session' ,'Provide an audio tool that will be used by a facilitator to deliver his vocal overview and textfields that contain all session information and scenario. ','Optional in all pedagogical techniques');


insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Presenting a question',17, 'similar to face-to-face sessions, how can a facilitator ask questions?','In some techniques, teacher start the session by presents a question to students which will be followed by another step, such as sharing that answer with peers ' ,'Provide  an answer box for the students to send their answers. A shared box to hold the answers of all the students. ','Think-pair-share');

insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Results Evaluation',19, 'How can a facilitator evaluate participants results?','Evaluation is an essential part at any teaching/learning process ' ,'Provide facilitators with a tool that contains: a text box to hold facilitators evaluation. All evaluation comments will be saved in a repository for any further review by the learners. ','Optional in all pedagogical techniques');

insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Small group discussions',22, 'How can a group of learners participate in a text/audio discussion chat ?','Many  activities imply that participants collaborate by using text/audio/video communication, to allow users to engage in multimedia-messaging conference.  The chat transcript is saved at a repository for further review and assessments. Some sessions need to anonymous to ease the social pressure  ' ,'Provide learners with a chat box/audio where  participants can contribute during the session. The turn for sending the contributions is defined by the facilitator during the design. ','Optional in all pedagogical techniques');

insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Entire session discussions',23, 'How can the entire learners in session participate in a text/audio discussion chat ?','Many  activities imply that all participants collaborate by using text/audio communication to allow all users to share ideas among the entire session.   ' ,'Provide learners with a chat box/audio/video where  all participants can contribute during the session. ','Optional in all pedagogical techniques');

insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Similar roles discussions',24, 'How can  learners with same roles discuss an issues between themselves  ?','Some  activities imply that certain roles need to discuss an issue , expert group, among themselves before sharing their knowledge with their original group' ,'Provide learners with a chat box/audio  where only learners with similar roles can access the floor. ','Jigsaw ');

insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Introducing each other /Ice breakering',27, 'How can  learners introduce themselves to others ?','Usually, facilitator likes  learners to introduce themselves before starting the activity ' ,'Provide learners with a chat box/audio/video  where only learners within the same group can access . ','Optional in all pedagogical techniques ');




insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Submitting own resolution/conclusion to facilitator',30, 'How can learners submit the summary of their results as a group to the facilitator?','Many activities imply that groups should submit their results to the facilitator for assessments  ' ,'Provide learners with a send box where they can submit their results on the end of the session. ','Optional in all pedagogical techniques');

insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Silent/Private thinking',28, 'How can learners think individually about an issue ?','Many activities imply that learners should start thinking privately on a posted issue before engaging in a group activity  ' ,'Provide learners with an empty page headed by the facilitator question. facilitator can post their question in a dynamic box  ','Optional in all pedagogical techniques');

insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Submitting own resolution/conclusion to others',29, 'How can learners submit their own  results  to other groups ?','Many activities imply that learners should submit their results to other groups for sharing the findings  ' ,'Provide learners with a send box where they can submit their own results ','Optional in all pedagogical techniques');

insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ( 'Debriefing',34, 'How can facilitators make a debriefing ?','Some activities imply that facilitator make a debriefing after learners engaged in a group discussion  ' ,'Provide facilitators with a chat box and audio  where he can send his debriefing to all learners participating in that session. ','Role Playing');

insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Ideas voting',35, 'How can learners vote on posted ideas to select the best idea?','Some   activities imply that participants should select a single idea to come up with the best solution. ' ,'Provide learners with a voting tool where he can assign marks with ideas scale (0-10). All member can see ideas marks. If the source of ideas is the facilitator, then he  should provide these ideas during the design time, but if the ideas source is learners then ideas will be collected from the idea listing tool ','Usually in the Nomination Group Technique');

insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('yes/no voting',36, 'How can learners participate into a side voting?','Many debating activities imply that participants should vote on which side of the controversial issue they support. It provides some kind of feedback mechanism needed by the debater or the facilitator  ' ,'Provide participants with voting tool that contains: a controversial question where the answer is yes or no, a yes/no button to choose from, and a percentage bars to reflect the voting results. ','Usually in the Debate, Pro/Contra Technique');

insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Writing a collaborative text',37, 'How can learners participate in writing a common text?','Some activities imply that participants should write a common text. It is their responsibility to organize among themselves to avoid writings collisions  ' ,'Provide participants with a shared text box and a led which will turn to red  when one participant start writing. All group members will see simultanly  the typed text    ','Optional in all pedagogical techniques');










insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ( 'Tracking participants interactions',7, 'How can facilitators and learners track participants  interactions ?','Usually, facilitator would like to monitor the participants interactions levels to provide guiding or assessments. While learners can compare their interaction levels with others for more encouragement  ' ,' Provide facilitators with a radar circle which represents all participants as dots trying to reach the center. User can retrieve user info by placing  the mouse over the desired dot. The user related dot will be flashing with -you- label  and with each contribution his dot will move  one step to the center. ','Optional in all pedagogical techniques');

insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Providing a vocal slides show',18, 'How can  facilitator provide a slides audio overview  at the beginning of the collaboration activity?','In sessions which require an introductory presentation' ,'Provide an audio tool that will be used by  facilitators to deliver their vocal overview, facilitator shared mouse to point to certain part of the slides, the slides which are power-point based images, and a chat box for asking questions. ','Optional in all pedagogical techniques');


insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Discussing the listed ideas',38, 'How can learners discuss posted ideas ?','Some   activities imply that participants should discuss ideas to come up with the best solution. ' ,'Provide learners with a chat tool for group discussion. a text box that hold the ideas  collected from the idea listing tool ','Usually in the Nomination Group Technique');


insert into beehive_tasks (name,num,problem,forces,solution,rpt) values ('Searching the internet',6, 'How can learners search the net for information needed in the session?', 'Occasionally during the session, facilitator would like learners to search for a specific information needed in the following steps of the session. ' ,' Provide a separate internet search page at the specific session step. ','Optional in all pedagogical techniques');






insert into beehive_patscript (techniqe,tname,n1, ins1,tr1,tl1,tool1,n2,ins2,tr2,tl2,tool2) values ('Group Discussion', 'default',1,'read related info ','all','000500','textInfo-EntireSession',2,'start discussion','all','001000','Disscussion-SmallGroup');

insert into beehive_pattern ( techniqe,name,roles,mx,mn,df,t12,t22,problem,example,context,gstructure,solution,adda1,addv1,adda2,addv2,adda3,addv3,btype1,btype2,anon1,anon2,anon3,anon4,uses,criticalthinking,  timemanagement,  writtencommunicatoin) values ('Group Discussion','default','participant', '5','5','5','checked' ,'checked','How to establish and encourage group knowledge sharing among students ', 'Discussing how to improve writing and speaking skills for a foreigner student ', 'Small groups with different skills and backgrounds interact to develop more knowledge among them ','Size: usually 5Structure: participants(5) ', '1- Teacher specify the discussion topic and related info.2- All student will start discussion according to their experience and may build upon others knowledge','checked',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ', 'Knowledge sharing','checked','checked','checked');



insert into beehive_patscript (techniqe,tname ,n1,ins1,tr1,tl1,tool1,n2,ins2,tr2,tl2,tool2,n3,ins3,tr3,tl3,tool3,n4,ins4,tr4,tl4,tool4,n5,ins5,tr5,tl5,tool5 ) values ('Round Table discussion', 'default',1,' ','participant1','000200','Disscussion-SmallGroup',2,' ','participant2','000200','Disscussion-SmallGroup',3,' ','participant3','000200','Disscussion-SmallGroup',4,' ','participant5','000200','Disscussion-SmallGroup',5,' ','participant5','000200','Disscussion-SmallGroup');

insert into beehive_pattern ( techniqe,name,roles,mx,mn,df,t22,problem,example,context,gstructure,solution,adda1,addv1,adda2,addv2,adda3,addv3,btype1,btype2,anon1,anon2,anon3,anon4,uses,criticalthinking,  timemanagement,  writtencommunicatoin ) values ('Round Table discussion','default','participant1/participant2/participant3/participant4/participant5', '5','5','5','checked','How to motivate balance participations across all members ','Discussing the advantages of E-Learning ','Generating new abstract understanding by enabling balance knowledge-sharing ','Size: usually 5Structure: participant1, participant2, participant3, participant4, participant5', '1- The first student on the list will be enabled to post a response 2- the next student will be enabled and so on','checked','checked',' ',' ',' ',' ','checked',' ',' ',' ',' ',' ', 'Knowledge sharing with a balanced participation','checked','checked','checked');



insert into beehive_patscript (techniqe,tname,n1, ins1,tr1,tl1,tool1,n2,ins2,tr2,tl2,tool2,n3,ins3,tr3,tl3,tool3,n4,ins4,tr4,tl4,tool4) values ('Group Nomination technique', 'default',1,'start brainstorming','all','001000','IdeasPosting-SmallGroup',2,'start discussion the ideas','all','000600','IdeasDiscussion-SmallGroup',3,'vote on ideas','all','000100','IdeasVoting-SmallGroup',4,'submit the result based on ideas rating','chairperson','000200','OwnResolution-EntireSession');

insert into beehive_pattern ( techniqe,name,roles,mx,mn,df,t26,t38,t35,t29,problem,example,context,gstructure,solution,adda1,addv1,adda2,addv2,adda3,addv3,btype1,btype2,anon1,anon2,anon3,anon4,uses,criticalthinking,  creativethinking, analyticalskills, decisionmaking, leadership, timemanagement   , oralcommunication  ,  writtencommunicatoin 
) values ('Group Nomination technique','default','chairperson/participant', '5','5','5','checked','checked','checked','checked','A certain topic or problem without a specific solution whose resolution implies not only creating ideas or solution, but also choosing the best idea   ','Generating and selecting a website project title for an E business course  ','Suitable for organizational decision making where different people with different skills and knowledge participating in creating, discussing, and then selecting.  ','Size: usually 5Structure: chairperson, participants(4)
time: 20 min ', '1-  posting  ideas; no criticism or elaboration is allowed in this stage.2- The next stage is discussing each recorded idea to obtain clarification and evaluation3- participant is asked to assign a mark for each idea 4- reporting the result based on ideas rating to other groups (by chairperson)','',' ',' ',' ',' ',' ','checked',' ',' ',' ',' ',' ','Creating and choosing the best ideas/solutions ','checked','checked','checked','checked','checked','checked','checked','checked');

insert into beehive_patscript (techniqe,tname,n1, ins1,tr1,tl1,tool1,n2,ins2,tr2,tl2,tool2) values ('Brainstorm', 'default',1,'read related info ','all','000500','textInfo-EntireSession',2,'start brainstorming','all','001000','IdeasPosting-SmallGroup');



insert into beehive_pattern ( techniqe,name,roles,mx,mn,df,t26,t12,problem,example,context,gstructure,solution,adda1,addv1,adda2,addv2,adda3,addv3,btype1,btype2,anon1,anon2,anon3,anon4, uses,creativethinking,  timemanagement,  writtencommunicatoin ) values ('Brainstorm','default','participant', '5','5','5','checked','checked','A certain topic or problem without a specific solution whose resolution implies generating many ideas form all members in short time  ','Generating different solutions for the reduction of electrical bills ','Motivate group to generate many creative new ideas and solutions by not allowing criticism or elaboration ','Size: usually 5Structure:  participants(5)
time: 20 min ', '1- Teacher gives students a background info 2- participants starts  posting their ideas; no criticism or elaboration is allowed in this stage.',' ',' ',' ',' ',' ',' ','checked',' ',' ',' ',' ',' ', 'Ideas creation in a short period','checked','checked','checked');




insert into beehive_patscript (techniqe,tname ,n1,ins1,tr1,tl1,tool1,n2,ins2,tr2,tl2,tool2,n3,ins3,tr3,tl3,tool3,n4,ins4,tr4,tl4,tool4,n5,ins5,tr5,tl5,tool5,n6,ins6,tr6,tl6,tool6,n7,ins7,tr7,tl7,tool7,n8,ins8,tr8,tl8,tool8  ) values ('Debate', 'default',1,'Propose the motion','proposer','000500','Disscussion-SmallGroup',2,'Second the Proposer','seconder(p)','000300','Disscussion-SmallGroup',3,'Oppose the motion','opposer','000500','Disscussion-SmallGroup',4,'Second the Opposer','seconder(o)','000300','Disscussion-SmallGroup',5,'Speak From The Floor','speakers','001000','Disscussion-SmallGroup',6,'Sum up for the motion','proposer','000300','Disscussion-SmallGroup',7,'Sum up for the opposition','opposer','000300','Disscussion-SmallGroup',8,'Do you support the proposor','all','000100','YesNo-EntireSession');

insert into beehive_pattern ( techniqe,name,roles,mx,mn,df,t22,t36,problem,example,context,gstructure,solution,adda1,addv1,adda2,addv2,adda3,addv3,btype1,btype2,anon1,anon2,anon3,anon4,uses,criticalthinking,  timemanagement,  writtencommunicatoin, decisionmaking) values ('Debate','default','proposer/seconder(p)/opposer/seconder(o)/speakers','10','10','10','checked','checked','How to clarify a controversial topic by presenting the best argument for or against the proposal   ','Discussing the issue of illegal workers in the USA and their impact on the USA economy in a business class ','Interaction strategy used to help student developing critical thinking and listening skills to make important decisions  ','Size: usually 10 Structure: proposer, second proposer,  opposer, second opposer, speakers(6)
time: 36min ', '1- Proposer will  propose the motion2- The second proposer will second the  proposer 3- The opposer will oppose the motion4- The second opposer will second the  opposer5- Speakers will participate  from The floor6- The proposer will sum up for the motion7- The opposer will sum up for  the opposition8- Voting on a particular side',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ', ' A controversial topic  clarification or decision making','checked','checked','checked','checked' );


insert into beehive_patscript (techniqe,tname ,n1,ins1,tr1,tl1,tool1,n2,ins2,tr2,tl2,tool2,n3,ins3,tr3,tl3,tool3,n4,ins4,tr4,tl4,tool4,n5,ins5,tr5,tl5,tool5,n6,ins6,tr6,tl6,tool6,n7,ins7,tr7,tl7,tool7,n8,ins8,tr8,tl8,tool8  ) values ('Problem Based Learning PBL', 'default',1,'Read the problem description ','all','000500','textInfo-EntireSession',2,'Identify concept and parts of the problem that needs clarification','all','000300','IndividualTextWriting-None',3,'Define the problem','all','000500','IndividualTextWriting-None',4,'Brainstorm  about solutions','all','000300','IdeasPosting-SmallGroup',5,'Structure solutions or causes','all','001000','IndividualTextWriting-None',6,'state learning objectives','all','000300','IndividualTextWriting-None',7,'Self study directed towards learning objectives ','all','001300','InternetSearch-None',8,'report things learned and application to problem','all','001000','SharedText-SmallGroup');

insert into beehive_pattern ( techniqe,name,roles,mx,mn,df,t6,t12,t26,t37,solution,adda1,addv1,adda2,addv2,adda3,addv3,btype1,btype2,anon1,anon2,anon3,anon4,uses,criticalthinking,  timemanagement,  writtencommunicatoin) values ('Problem Based Learning PBL','default','participant','5','5','5','checked','checked','checked','checked', '1- Reading the problem description 2- Identifying  concept and parts of the problem that needs clarification 3- Defining the problem 4- Brainstorming  about solutions 5- Structuring solutions or causes 6- stating learning objectives 7- Self studying directed towards learning objectives 8- reporting things learned and application to problem',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ', ' to actively involve with problems coming from real practice','checked','checked','checked' );




insert into beehive_patscript (techniqe,tname,n1, ins1,tr1,tl1,tool1,n2,ins2,tr2,tl2,tool2,n3,ins3,tr3,tl3,tool3) values ('Jigsaw', 'default',1,'study a particular sub problem','all','001000','textInfo-Role',2,'exchanging ideas with your expert groups ','all','001000','Disscussion-Roles',3,'jigsaw group participants meet to solve the whole problem','all','001500','Disscussion-SmallGroup');

insert into beehive_pattern ( techniqe,name,roles,mx,mn,df,t22,t13,t24,problem,example,context,gstructure,solution,adda1,addv1,adda2,addv2,adda3,addv3,btype1,btype2,anon1,anon2,anon3,anon4,uses,criticalthinking,  timemanagement,  writtencommunicatoin, analyticalskills) values ('Jigsaw','default',' ', '5','5','5','checked','checked','checked','A complex problem whose resolution requires handling information that can be divided in disjoint sets and used for the resolution of independent sub problems  ','Collaborative Design of a computer system, where each subsystem is assigned to an individual ','Several small groups facing the study of a large amount of information for the resolution of the same problem','Size: usually 5 ', '1- Teacher gives  a specific period of time for each participant in the group (jigsaw group) to study a particular sub problem.2- The participants of different groups that study the same problem meet in expert groups for exchanging ideas3- At last, jigsaw group participants meet to solve the whole problem','checked',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','Complex Problem solving','checked','checked','checked','checked');


insert into beehive_patscript (techniqe,tname,n1, ins1,tr1,tl1,tool1,n2,ins2,tr2,tl2,tool2,n3,ins3,tr3,tl3,tool3) values ('Pro/Contra', 'default',1,'study a particular issue side ','all','001000','textInfo-Role',2,'exchanging ideas with your side group ','all','001000','Disscussion-Roles',3,'the whole group participants meet to discuss and argue','all','001500','Disscussion-SmallGroup');

insert into beehive_pattern ( techniqe,name,roles,mx,mn,df,t22,t13,t24,context,gstructure,solution,adda1,addv1,adda2,addv2,adda3,addv3,btype1,btype2,anon1,anon2,anon3,anon4,dtype1,uses,criticalthinking,  timemanagement,  writtencommunicatoin, analyticalskills) values ('Pro/Contra','default','Pro/Contra/Pro/Contra/Pro/Contra/Pro/Contra/Pro/Contra', '10','10','10','checked','checked','checked','Motivate ','Size: usually 10Structure: Pro(5), Contra(5) ', '1- Teacher gives  a specific period of time for each participant in the group to study a particular side of an issue.2- Each side start their own discussion.3- When the discussion is completed the result is shared and discussed with the other side group','checked',' ',' ',' ',' ',' ','  ',' ',' ',' ',' ',' ','checked','Understanding and presenting different sides views','checked','checked','checked','checked');


insert into beehive_patscript (techniqe,tname,n1, ins1,tr1,tl1,tool1,n2,ins2,tr2,tl2,tool2,n3,ins3,tr3,tl3,tool3) values ('Think Pair Share', 'default',1,'think silently about this question  ','all','001000','textInfo-EntireSession',2,'exchanging ideas with your partner','all','001000','Disscussion-SmallGroup',3,'exchange ideas with the whole session','all','001500','Disscussion-EntireSession');

insert into beehive_pattern ( techniqe,name,roles,mx,mn,df,t12,t22,t23,gstructure,solution,adda1,addv1,adda2,addv2,adda3,addv3,btype1,btype2,anon1,anon2,anon3,anon4,uses,criticalthinking,  timemanagement,  writtencommunicatoin, analyticalskills) values ('Think Pair Share', 'default','participant', '2','2','2','checked','checked','checked','Size: usually 2', '1- Each participant think silently about question posed.2- Individual pair up during the second step and exchange thoughts3- The pair share their responses with the entire group','checked',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','Content that requires individual reflection, peer discussion and  groups solutions sharing','checked','checked','checked','checked');



insert into beehive_patscript (techniqe,tname,n1, ins1,tr1,tl1,tool1,n2,ins2,tr2,tl2,tool2,n3,ins3,tr3,tl3,tool3) values ('Pyramid', 'default',1,'think silently about question posed ','all','001000','textInfo-EntireSession',2,'exchanging ideas with your partners','all','001000','Disscussion-SmallGroup',3,'exchange ideas with the whole session','all','001500','SharedText-EntireSession');

insert into beehive_pattern ( techniqe,name,roles,mx,mn,df,t12,t22,t10,solution,adda1,addv1,adda2,addv2,adda3,addv3,btype1,btype2,anon1,anon2,anon3,anon4,uses,criticalthinking,  timemanagement,  writtencommunicatoin, analyticalskills) values ('Pyramid', 'default','participant', '5','5','5','checked','checked','checked', '1- Each participant think silently about question posed.2- Individual  exchange thoughts with their group3- Then they shared  responses with the entire session','checked',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','Content that requires  individual reflection and then multiple levels of group discussion and explanation','checked','checked','checked','checked');


insert into beehive_patscript (techniqe,tname,n1, ins1,tr1,tl1,tool1,n2,ins2,tr2,tl2,tool2,n3,ins3,tr3,tl3,tool3) values ('Buzz Group', 'default',1,'reading the group info','all','001000','textInfo-SmallGroup',2,'exchanging ideas with your partners','all','001000','Disscussion-SmallGroup',3,'submit your own resolution','chairperson','001500','SharedText-EntireSession');

insert into beehive_pattern ( techniqe,name,roles,mx,mn,df,t10,t4,t22,solution,adda1,addv1,adda2,addv2,adda3,addv3,btype1,btype2,anon1,anon2,anon3,anon4,uses,criticalthinking,  timemanagement,  writtencommunicatoin, leadership) values ('Buzz Group', 'default','chairperson/participant', '5','3','3','checked','checked','checked', '1- Individual  exchange thoughts with their group. 2- Each group should submit his own resolution','checked',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','A topic group  discussion  for a short period to gather potential solutions to a problem','checked','checked','checked','checked');


insert into beehive_patscript (techniqe,tname,n1, ins1,tr1,tl1,tool1,n2,ins2,tr2,tl2,tool2,n3,ins3,tr3,tl3,tool3) values ('Role Playing', 'default',1,'each role read his info','all','001000','textInfo-Role',2,'each role should start role palying ','all','001000','Disscussion-SmallGroup',3,'Debrifing','all','000300','Debriefing-EntireSession');

insert into beehive_pattern ( techniqe,name,roles,mx,mn,df,t13,t22,t34,solution,adda1,addv1,adda2,addv2,adda3,addv3,btype1,btype2,anon1,anon2,anon3,anon4,uses,criticalthinking,  timemanagement,  writtencommunicatoin, analyticalskills, oralcommunication) values ('Role Playing', 'default','role1/role2/audience', '5','5','5','checked','checked','checked', '1- Each participant with a role start acting.2- facilitator and participants discuss the situation and various perspective of the individual characters ','checked',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','Training/ Understanding the different aspects of a topic ','checked','checked','checked','checked','checked');


insert into beehive_patscript (techniqe,tname,n1, ins1,tr1,tl1,tool1,n2,ins2,tr2,tl2,tool2,n3,ins3,tr3,tl3,tool3) values ('Case Studes', 'default',1,'read/watch the uploaded file','all','002000','DownloadFile-EntireSession',2,'question 1','all','000300','QA-EntireSession',3,'question 2','all','000300','QA-EntireSession');




insert into beehive_pattern ( techniqe,name,roles,mx,mn,df,t2,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14,t15,t17,t18,t19,t20,t22,t23,t24,t26,t27,t28,t29,t30,t31,t32,t33,t34,t35,t36,t37,t38,ctype1,ctype2,ctype3,controlld1,controlld2,problem,example,context,gstructure,solution,adda1,addv1,adda2,addv2,adda3,addv3,btype1,btype2,anon1,anon2,anon3,anon4,uses,  timemanagement,  writtencommunicatoin, analyticalskills) values ('Case Studes', 'default','participant', '5','5','5',' ',' ',' ','  ','  ','  ',' ','  ',' ','  ',' ',' ','  ', 'checked','  ','  ','  ', ' ', '  ','  ',' ','  ',' ',' ',' ',' ','  ','checked',' ',' ','  ','   ','   ',' ',' ',' ',' ',' ', '     ','    ','A story or situation is written for learners to read and consider. It may be presented on paper, read or seen on video ',' ', '1- Each participant read or watch the related material .2- Each participant should submit his own resolution of a proposed question',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','Helping participants to develop skills in identifying concerns, analyzing problems, and considering solutions','checked','checked','checked');


insert into beehive_patscript (techniqe,tname,n1, ins1,tr1,tl1,tool1,n2,ins2,tr2,tl2,tool2,n3,ins3,tr3,tl3,tool3) values ('Team Pair Solo', 'default',1,'entire session discuss the issue','all','001000','Disscussion-EntireSession',2,'exchanging ideas with your partner','all','001000','Disscussion-SmallGroup',3,'submit your own resolution','all','000300','OwnResolution-EntireSession');

insert into beehive_pattern ( techniqe,name,roles,mx,mn,df,t22,t23,t29,context,gstructure,solution,adda1,addv1,adda2,addv2,adda3,addv3,btype1,btype2,anon1,anon2,anon3,anon4,uses,criticalthinking,  timemanagement,  writtencommunicatoin) values ('Team Pair Solo', 'default','participant', '2','2','2','checked','checked','checked','Motivate ','Size: usually 2', '1- The entire session discuss an issue2- Individuals pair up during the second step and exchange thoughts3- Each participant should submit his own resolution.','checked',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','Content that requires group discussion, peer explanation, and finally individual reflection','checked','checked','checked');

insert into beehive_patscript (techniqe,tname,n1, ins1,tr1,tl1,tool1,n2,ins2,tr2,tl2,tool2) values ('Presentation', 'default',1,'entire session watch the slides','facilitator','001000','Slides-EntireSession',2,'discussion and questioning','all','001000','Disscussion-EntireSession');

insert into beehive_pattern ( techniqe,name,roles,mx,mn,df,t18,t23,context,gstructure,solution,adda1,addv1,adda2,addv2,adda3,addv3,btype1,btype2,anon1,anon2,anon3,anon4,uses,criticalthinking,  timemanagement,  writtencommunicatoin) values ('Presentation', 'default','participant', '20','20','20','checked','checked','Motivate ','Size: usually 2', '1- The Facilitator present slides with his narration 2- The entire session discussion regarding the presentation ',' ','checked',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ','Content that requires presentation',' ','checked','checked');


insert into beehive_patscript (techniqe,tname ,n1,ins1,tr1,tl1,tool1,n2,ins2,tr2,tl2,tool2,n3,ins3,tr3,tl3,tool3,n4,ins4,tr4,tl4,tool4,n5,ins5,tr5,tl5,tool5,n6,ins6,tr6,tl6,tool6,n7,ins7,tr7,tl7,tool7,n8,ins8,tr8,tl8,tool8,n9,ins9,tr9,tl9,tool9,n10,ins10,tr10,tl10,tool10,n11,ins11,tr11,tl11,tool11,n12,ins12,tr12,tl12,tool12,n13,ins13,tr13,tl13,tool13,n14,ins14,tr14,tl14,tool14 ) values ('Debate', ' Three Person Team Debate Format (Mount Holyoke College) ',1, 'N1 Affirmative Debater s Constructive Speech ','N1Affirmative','000400','Disscussion-SmallGroup',2,'N2 Affirmative Debater s Constructive Speech ', 'N2Affirmative','000400','Disscussion-SmallGroup',3,'N1 Negative Debater s Constructive Speech ','N1Negative','000400','Disscussion-SmallGroup',4,'N2 Negative Debater s Constructive Speech ','N2Negative','000400','Disscussion-SmallGroup',5,'N3 Affirmative Debater s Constructive Speech ','N3Affirmative','000400','Disscussion-SmallGroup',6,'N3 Negative Debater s Constructive Speech ','N3Negative','000400','Disscussion-SmallGroup',7,'Brief preparation time ','all','000500','IndividualWriting',8, 'N2 Negative Debater s Rebuttal Speech ','N2Negative','000300','Disscussion-SmallGroup',9,'N2 Affirmative Debater s Rebuttal Speech ', 'N2Affirmative','000300','Disscussion-SmallGroup',10,'N1 Negative Debater s Constructive Speech ',' N1Negative','000300','Disscussion-SmallGroup',11,'N1 Affirmative Debater s Rebuttal Speech ','N1Affirmative','000300','Disscussion-SmallGroup',12,'N3 Negative Debater s Rebuttal Speech ','N3Negative','000300','Disscussion-SmallGroup',13,'N3 Affirmative Debater s Rebuttal Speech ','N3Affirmative','000100','Disscussion-SmallGroup',14,'Audience Questioning ','all','001500','Disscussion-SmallGroup');

insert into beehive_patscript (techniqe,tname ,n1,ins1,tr1,tl1,tool1,n2,ins2,tr2,tl2,tool2,n3,ins3,tr3,tl3,tool3,n4,ins4,tr4,tl4,tool4,n5,ins5,tr5,tl5,tool5,n6,ins6,tr6,tl6,tool6,n7,ins7,tr7,tl7,tool7,n8,ins8,tr8,tl8,tool8,n9,ins9,tr9,tl9,tool9,n10,ins10,tr10,tl10,tool10 ) values ('Debate', ' Two Person Team Debate Format (Mount Holyoke College) ',1, 'N1 Affirmative Debater s Constructive Speech ','N1Affirmative','000400','Disscussion-SmallGroup',2,'N1 Negative Debater s Constructive Speech ','N1Negative','000400','Disscussion-SmallGroup',3,'N2 Affirmative Debater s Constructive Speech ', 'N2Affirmative','000400','Disscussion-SmallGroup',4,'N2 Negative Debater s Constructive Speech ','N2Negative','000400','Disscussion-SmallGroup',5,'Brief preparation time ','all','000500','IndividualWriting',6,'N1 Negative Debater s Constructive Speech ',' N1Negative','000300','Disscussion-SmallGroup',7,'N1 Affirmative Debater s Rebuttal Speech ','N1Affirmative','000300','Disscussion-SmallGroup',8, 'N2 Negative Debater s Rebuttal Speech ','N2Negative','000300','Disscussion-SmallGroup',9,'N2 Affirmative Debater s Rebuttal Speech ', 'N2Affirmative','000300','Disscussion-SmallGroup',10,'Audience Questioning ','all','001500','Disscussion-SmallGroup');

insert into beehive_patscript (techniqe,tname ,n1,ins1,tr1,tl1,tool1,n2,ins2,tr2,tl2,tool2,n3,ins3,tr3,tl3,tool3,n4,ins4,tr4,tl4,tool4,n5,ins5,tr5,tl5,tool5,n6,ins6,tr6,tl6,tool6,n7,ins7,tr7,tl7,tool7 ) values ('Debate', ' A typical Oxford format ',1, '1st Negative (constructive and rebuttal speech) ','N1Affirmative','000400','Disscussion-SmallGroup',2,'1st Negative (constructive and rebuttal speech)', 'N1Negative','000400','Disscussion-SmallGroup',3,'2nd Affirmative (constructive and rebuttal speech)','N2Affirmative','000400','Disscussion-SmallGroup',4,' 4- 2nd Negative (constructive and rebuttal speech)','N2Negative','000400','Disscussion-SmallGroup',5,'3rd Affirmative (constructive and rebuttal speech)','N3Affirmative','000400','Disscussion-SmallGroup',6,'3rd Negative (constructive and rebuttal speech) ','N3Negative','000400','Disscussion-SmallGroup',7,'N1 Affirmative  Rebuttal Speech ','N1Affirmative','000300','Disscussion-SmallGroup');

insert into beehive_patscript (techniqe,tname ,n1,ins1,tr1,tl1,tool1,n2,ins2,tr2,tl2,tool2,n3,ins3,tr3,tl3,tool3,n4,ins4,tr4,tl4,tool4,n5,ins5,tr5,tl5,tool5,n6,ins6,tr6,tl6,tool6,n7,ins7,tr7,tl7,tool7,n8,ins8,tr8,tl8,tool8,n9,ins9,tr9,tl9,tool9,n10,ins10,tr10,tl10,tool10 ) values ('Debate', ' Modified Oxford format ',1, ' 1-  1st Affirmative (constructive speech)','N1Affirmative','000400','Disscussion-SmallGroup',2,'Cross-examination by 2nd Negative', 'N2Negative','000400','Disscussion-SmallGroup',3,'1st Negative (constructive speech)','N1Negative','000400','Disscussion-SmallGroup',4,'Cross-examination by 1st Affirmative)','N1Affirmative','000400','Disscussion-SmallGroup',5,'2nd Affirmative (constructive speech)','N2Affirmative','000400','Disscussion-SmallGroup',6,'Cross-examination by 1st Negative)','N1Negative','000400','Disscussion-SmallGroup',7,'2nd Negative (constructive speech) ', 'N2Affirmative','000300','Disscussion-SmallGroup',8,'Cross Examination by 2nd Affirmative',' N2Affirmative','000300','Disscussion-SmallGroup',9,'1st Negative (rebuttal-defence-summary speech)','N1Negative','000300','Disscussion-SmallGroup',10,'1st Affirmative (rebuttal-defence-summary speech)','N1Affirmative','000300','Disscussion-SmallGroup');

insert into beehive_patscript (techniqe,tname ,n1,ins1,tr1,tl1,tool1,n2,ins2,tr2,tl2,tool2,n3,ins3,tr3,tl3,tool3,n4,ins4,tr4,tl4,tool4,n5,ins5,tr5,tl5,tool5,n6,ins6,tr6,tl6,tool6,n7,ins7,tr7,tl7,tool7,n8,ins8,tr8,tl8,tool8,n9,ins9,tr9,tl9,tool9,n10,ins10,tr10,tl10,tool10,n11,ins11,tr11,tl11,tool11,n12,ins12,tr12,tl12,tool12 ) values ('Debate', ' A typical Cambridge format ',1, 'N1 Affirmative Debater s Constructive Speech ','N1Affirmative','000400','Disscussion-SmallGroup',2,'N1 Negative Debater s Constructive Speech ','N1Negative','000400','Disscussion-SmallGroup',3,'N2 Affirmative Debater s Constructive Speech ', 'N2Affirmative','000400','Disscussion-SmallGroup',4,'N2 Negative Debater s Constructive Speech ','N2Negative','000400','Disscussion-SmallGroup',5,'N3 Affirmative Debater s Constructive Speech ', 'N3Affirmative','000400','Disscussion-SmallGroup',6,'N3 Negative Debater s Constructive Speech ','N3Negative','000400','Disscussion-SmallGroup',7,'N1 Negative Debater s Rebuttal Speech ',' N1Negative','000400','Disscussion-SmallGroup',8,'N1 Affirmative Debater s Rebuttal Speech ','N1Affirmative','000400','Disscussion-SmallGroup',9, 'N2 Negative Debater s Rebuttal Speech ','N2Negative','000400','Disscussion-SmallGroup',10,'N2 Affirmative Debater s Rebuttal Speech ', 'N2Affirmative','000400','Disscussion-SmallGroup',11, 'N3 Negative Debater s Rebuttal Speech ','N2Negative','000400','Disscussion-SmallGroup',12,'N3 Affirmative Debater s Rebuttal Speech ', 'N3Affirmative','000400','Disscussion-SmallGroup');


insert into beehive_pattern ( techniqe,name,roles,mx,mn,df,t22,problem,example,context,gstructure,solution,adda1,addv1,adda2,addv2,adda3,addv3,btype1,btype2,anon1,anon2,anon3,anon4,uses) values ('Debate','Three Person Team Debate Format', 'N1Affirmative/N2Affirmative/N3Affirmative/N1Negative/N2Negative/N3Negative/Audience' ,'12','12','12','checked','How to clarify a controversial topic by presenting the best argument for or against the proposal   ','Discussing the issue of illegal workers in the USA and their impact on the USA economy in a business class ','Interaction strategy used to help student developing critical thinking and listening skills to make important decisions  ','Size: usually 12 Structure: N1 Affirmative, N2 Affirmative, N3 Affirmative, N1 Negative, N2 Negative, N3 Negative, Audience (6)
time: 60 min', '1- N1 Affirmative Debaters Constructive Speech 2- N2 Affirmative DebaterÕs Constructive Speech 3- N1 Negative DebaterÕs Constructive Speech  4- N2 Negative DebaterÕs Constructive Speech  5- N3 Affirmative Debaters Constructive Speech  6- N3 Negative Debaters Constructive Speech  7-  Brief preparation time 8- N2 Negative Debaters Rebuttal Speech 9- N2 Affirmative Debaters Rebuttal Speech 10- N1 Negative Debaters Rebuttal Speech  11- N1 Affirmative Debaters Rebuttal Speech 12- N3 Negative DebaterÕs Rebuttal Speech  13- N3 Affirmative Debaters Rebuttal Speech  14- Audience Questioning ','checked',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ');

insert into beehive_pattern ( techniqe,name,roles, mx,mn,df,t22,problem,example,context,gstructure,solution,adda1,addv1,adda2,addv2,adda3,addv3,btype1,btype2,anon1,anon2,anon3,anon4,uses) values ('Debate','Two Person Team Debate Format', 'N1Affirmative/N2Affirmative/N1Negative/N2Negative/Audience' ,'10','10','10','checked','How to clarify a controversial topic by presenting the best argument for or against the proposal   ','Discussing the issue of illegal workers in the USA and their impact on the USA economy in a business class ','Interaction strategy used to help student developing critical thinking and listening skills to make important decisions  ','Size: usually 10 Structure: N1 Affirmative, N2 Affirmative, N1 Negative, N2 Negative, Audience (6)
time: 48 min', '1- N1 Affirmative Debater s Constructive Speech 2- N1 Negative Debater s Constructive Speech  3- N2 Affirmative Debater s Constructive Speech4- N2 Negative Debater s Constructive Speech  5-  Brief preparation time 6- N1 Negative Debater s Rebuttal Speech  7- N1 Affirmative Debater s Rebuttal Speech 8- N2 Negative Debater s Rebuttal Speech 9- N2 Affirmative Debater s Rebuttal Speech 10- Audience Questioning','checked',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ');

insert into beehive_pattern (techniqe, name,roles,mx,mn,df,t22,problem,example,context,gstructure,solution,adda1,addv1,adda2,addv2,adda3,addv3,btype1,btype2,anon1,anon2,anon3,anon4,uses) values ('Debate','A typical Oxford format ', 'N1Affirmative/N2Affirmative/N3Affirmative/N1Negative/N2Negative/N3Negative/Audience' ,'12','12','12','checked','How to clarify a controversial topic by presenting the best argument for or against the proposal   ','Discussing the issue of illegal workers in the USA and their impact on the USA economy in a business class ','Interaction strategy used to help student developing critical thinking and listening skills to make important decisions  ','Size: usually 12 Structure: N1 Affirmative, N2 Affirmative, N3 Affirmative, N1 Negative, N2 Negative, N3 Negative, Audience (6)
time:28 min', '1- 1st Affirmative (constructive speech)  2- 1st Negative (constructive and rebuttal speech)  3- 2nd Affirmative (constructive and rebuttal speech)  4- 2nd Negative (constructive and rebuttal speech)  5- 3rd Affirmative (constructive and rebuttal speech)  6- 3rd Negative (constructive and rebuttal speech)  7- 1st Affirmative (rebuttal speech) ','checked',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ');

insert into beehive_pattern ( techniqe,name,roles,mx,mn,df,t22,problem,example,context,gstructure,solution,adda1,addv1,adda2,addv2,adda3,addv3,btype1,btype2,anon1,anon2,anon3,anon4,uses) values ('Debate',' Modified Oxford format ', 'N1Affirmative/N2Affirmative/N1Negative/N2Negative/Audience' ,'12','12','12','checked','How to clarify a controversial topic by presenting the best argument for or against the proposal   ','Discussing the issue of illegal workers in the USA and their impact on the USA economy in a business class ','Interaction strategy used to help student developing critical thinking and listening skills to make important decisions  ','Size: usually 10 Structure: N1 Affirmative, N2 Affirmative, N1 Negative, N2 Negative, Audience (6)
time: 40 min', ' 1-  1st Affirmative (constructive speech)  2-  Cross-examination by 2nd Negative  3-  1st Negative (constructive speech)  4-  Cross-examination by 1st Affirmative)  5-  2nd Affirmative (constructive speech)  6-  Cross-examination by 1st Negative)  7-  2nd Negative (constructive speech)  8-  Cross Examination by 2nd Affirmative  9- 1st Negative (rebuttal-defence-summary speech)  10- 1st Affirmative (rebuttal-defence-summary speech) ','checked',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ');

insert into beehive_pattern ( techniqe,name,roles,mx,mn,df,t22,problem,example,context,gstructure,solution,adda1,addv1,adda2,addv2,adda3,addv3,btype1,btype2,anon1,anon2,anon3,anon4,uses) values ('Debate',' A typical Cambridge format ', 'N1Affirmative/N2Affirmative/N3Affirmative/N1Negative/N2Negative/N3Negative/Audience' ,'12','12','12','checked','How to clarify a controversial topic by presenting the best argument for or against the proposal   ','Discussing the issue of illegal workers in the USA and their impact on the USA economy in a business class ','Interaction strategy used to help student developing critical thinking and listening skills to make important decisions  ','Size: usually 12 Structure: N1 Affirmative, N2 Affirmative, N3 Affirmative, N1 Negative, N2 Negative, N3 Negative, Audience (6)
time: 48 min ', ' 1- 1st Affirmative (constructive speech)  2- 1st Negative (constructive speech)  3- 2nd Affirmative (constructive speech)  4- 2nd Negative (constructive speech)  5- 3rd Affirmative (constructive speech)  6- 3rd Negative (constructive speech)  7- 1st Negative (rebuttal speech)  8- 1st Affirmative (rebuttal speech)  9- 2nd Negative (rebuttal speech)  10- 2nd Affirmative (rebuttal speech)  11- 3rd Negative (rebuttal speech)  12- 3rd Affirmative (rebuttal speech) ','checked',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ');


